all:
  children:
    # _____ nodes by server type; not to be used directly _____
    local_machine:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: 127.0.0.1
          ansible_fqdn: localhost

    # _____ nodes by product; use these for playbooks _____
    cpp:
      children:
        local_machine:
