---

root_password: default
user_name: dev
user_password: default

# TODO: Structure containers as a list?
# Example Usage: "{{ (containers_alt | selectattr('name', 'equalto', 'Base') | first).container_file }}"
# containers_alt:
#   - name: Caddy
#   - name: Base
#     hostname: Dev-Environment
#     container_file: "{{ ansible_config_file | dirname }}/containers/base/ubuntu.base.container"
#     base_image:
#       registry: docker.io
#       name: ubuntu
#       tag: latest
#     image:
#       registry: localhost
#       name: base
#       tag: latest
#     ports:
#       - "10000:22"
#     volumes:
#       - "/home/andrew/workspace:/workspace"
#   - name: Cpp
#   - name: Node
#   - name: Python3

containers:
  caddy:
  base:
    name: dev
    hostname: Dev-Environment
    container_file: "{{ ansible_config_file | dirname }}/containers/base/ubuntu.base.container"
    base_image:
      registry: docker.io
      name: ubuntu
      tag: latest
    image:
      registry: localhost
      name: base
      tag: latest
    ports:
      - "10000:22"
    volumes:
      - "/home/andrew/workspace:/workspace"
  cpp:
    name: cpp
    hostname: Cpp-Environment
    container_file: "{{ ansible_config_file | dirname }}/containers/cpp/ubuntu.cpp.container"
    base_image:
      registry: localhost
      name: base
      tag: latest
    image:
      registry: localhost
      name: cpp
      tag: latest
    ports:
      - "20000:22"
    volumes:
      - "/home/andrew/workspace:/workspace"
  node:
    name: node
    hostname: Node-Environment
    container_file: "{{ ansible_config_file | dirname }}/containers/node/ubuntu.node.container"
    base_image:
      registry: localhost
      name: base
      tag: latest
    image:
      registry: localhost
      name: node
      tag: latest
    ports:
      - "30000:22"
    volumes:
      - "/home/andrew/workspace:/workspace"
  python3:
    name: python3
    hostname: Python3-Environment
    container_file: "{{ ansible_config_file | dirname }}/containers/python/ubuntu.python3.container"
    base_image:
      registry: localhost
      name: base
      tag: latest
    image:
      registry: localhost
      name: python3
      tag: latest
    ports:
      - "40000:22"
    volumes:
      - "/home/andrew/workspace:/workspace"
