---

- name: Building the container
  containers.podman.podman_image:
    name: "{{ dev_image_name }}"
    tag: "{{ dev_image_tag }}"
    path: "{{ __dev_container_dir }}"
    state: build
    force: "{{ dev_force_build | bool }}"
    build:
      # TODO: Provide build args as a list
      extra_args: >
        -f "{{ __dev_container_file }}"
        {% for arg in dev_build_args %}
        --build-arg="{{ arg }}"
        {% endfor %}
  tags:
    - build
