---
# Main tasks file for dev enviroment

- include_tasks:
    file: "{{ role_path }}/tasks/build.yml"
  tags:
    - build

- include_tasks:
    file: "{{ role_path }}/tasks/stop.yml"
  tags:
    - stop
    - restart

- include_tasks:
    file: "{{ role_path }}/tasks/start.yml"
  tags:
    - start
    - restart
