---
# Restart dev enviroment

- include_tasks:
    file: "{{ role_path }}/tasks/stop.yml"
  tags:
    - stop
    - restart

- include_tasks:
    file: "{{ role_path }}/tasks/start.yml"
  tags:
    - start
    - restart