---

- hosts: ubuntu
  tasks:
    - name: Building the base container image
      include_tasks:
        file: tasks/build_base.yml
      tags:
        - build

    - name: Running the Base container actions
      include_role:
        name: dev_env
        tasks_from: restart.yml
      vars:
        dev_container_name: "{{ base.name }}"
        dev_container_hostname: "{{ base.hostname }}"
        dev_image_name: "{{ base.image.name }}"
        dev_image_tag: "{{ base.image.tag }}"
        dev_port_mappings: "{{ base.ports }}"
        dev_volume_mappings: "{{ base.volumes }}"
        dev_recreate_container: true
      tags:
        - start
        - stop
        - restart
