---

- hosts: cpp
  tasks:
    - name: Building the base container image
      include_tasks:
        file: tasks/build_base.yml
      tags:
        - build

    - name: Running the C++ container actions
      include_role:
        name: dev_env
      vars:
        dev_image_name: "{{ cpp.image.name }}"
        dev_image_tag: "{{ cpp.image.tag }}"
        # Build variables
        dev_container_file: "{{ cpp.container_file }}"
        dev_build_args:
          - BASE_IMG_URL={{ cpp.base_image.registry }}/{{ cpp.base_image.name }}
          - BASE_IMG_TAG={{ cpp.base_image.tag }}
        dev_force_build: true
        # Run variables
        dev_container_name: "{{ cpp.name }}"
        dev_container_hostname: "{{ cpp.hostname }}"
        dev_port_mappings: "{{ cpp.ports }}"
        dev_volume_mappings: "{{ cpp.volumes }}"
        dev_recreate_container: true
      tags:
        - build
        - start
        - stop
        - restart
