---

- hosts: node
  tasks:
    - name: Building the base container image
      include_tasks:
        file: tasks/build_base.yml
      tags:
        - build

    - name: Running the Node container actions
      include_role:
        name: dev_env
      vars:
        dev_image_name: "{{ node.image.name }}"
        dev_image_tag: "{{ node.image.tag }}"
        # Build variables
        dev_container_file: "{{ node.container_file }}"
        dev_build_args:
          - BASE_IMG_URL={{ node.base_image.registry }}/{{ node.base_image.name }}
          - BASE_IMG_TAG={{ node.base_image.tag }}
        dev_force_build: true
        # Run variables
        dev_container_name: "{{ node.name }}"
        dev_container_hostname: "{{ node.hostname }}"
        dev_port_mappings: "{{ node.ports }}"
        dev_volume_mappings: "{{ node.volumes }}"
        dev_recreate_container: true
      tags:
        - build
        - start
        - stop
        - restart
