---

- hosts: python3
  tasks:
    - name: Building the base container image
      include_tasks:
        file: tasks/build_base.yml
      tags:
        - build

    - name: Running the Python3 container actions
      include_role:
        name: dev_env
      vars:
        dev_container_name: "{{ containers.python3.name }}"
        dev_container_hostname: "{{ containers.python3.hostname }}"
        dev_image_name: "{{ containers.python3.image.name }}"
        dev_image_tag: "{{ containers.python3.image.tag }}"
        dev_port_mappings: "{{ containers.python3.ports }}"
        dev_volume_mappings: "{{ containers.python3.volumes }}"
        dev_recreate_container: true
      tags:
        - start
        - stop
        - restart